### ISSUE TITLE
Replace Selenium2 driver this Facebook on proprietary test suite  

### ISSUE THREAD

**Issue by oleg-andreyev** [oleg-andreyev/MinkPhpWebDriver#1]
Going to an experiment on a proprietary test suite where we have 4k unique scenarios.
Project is running Symfony 2.8 (upgrading to 3.4 now)

We'll see how it goes.

**Comment by andrewnicols** [comment]
We have 2,500 scenarios too and I've kicked off a run against this driver.

https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/7179/console

Note: Some of the failures will be local and unrelated to this Driver, though so far all of the ones I've looked have been down to the driver (specifically #5).

**Comment by oleg-andreyev** [comment]
Looks awesome!
For me, it's a bit complicated due to the scale of the system, but I'll try to gather some results by the end of this week.

**Comment by oleg-andreyev** [comment]
No longer work at that company, don't have access to large test suite.
