### ISSUE TITLE
Add a Changelog.md

### ISSUE THREAD

**Issue by andrewnicols** [oleg-andreyev/MinkPhpWebDriver#14]
There is an existing Changelog file, but it hasn't been updated in some time.

I'd suggest that we scrap it and replace it with a new Changelog.md following the recommendations of https://keepachangelog.com/en/1.0.0/.

**Comment by oleg-andreyev** [comment]
yes. using it even in internal projects, as soon as "blocker" PR will be resolved, will create a changelog start from 1.0.x
