### ISSUE TITLE
Time to release..?

### ISSUE THREAD

**Issue by andrewnicols** [oleg-andreyev/MinkPhpWebDriver#29]
Any chance we can formally release on packagist to make use easier? We're about to go live with the driver with Moodle.

**Comment by oleg-andreyev** [comment]
I'm going to review all the changes, prepare changelog, review packagist and will try to release on this weekends.

**Comment by oleg-andreyev** [comment]
@andrewnicols released.
https://packagist.org/packages/oleg-andreyev/mink-php-web-driver#v1.0.0
