### ISSUE TITLE
Move project to php-webdriver/MinkPhpWebDriver

### ISSUE THREAD

**Issue by andrewnicols** [oleg-andreyev/MinkPhpWebDriver#4]
When @OndraM moved the php-webdriver from `facebook/php-webdriver` to `php-webdriver/php-webdriver` there was some discussion about the naming of the project there in relation to other projects (https://github.com/php-webdriver/php-webdriver/issues/730#issuecomment-571362826_).

To improve the sustainability of this project I feel that it might be worth moving it to be under the `php-webdriver` organisation. Ideally we should also update the namespace (sorry @oleg-andreyev).

Another alternative would be to move it under the MinkPHP project (@stof), but I feel that it makes more sense to link the Mink driver to the underlying Webdriver implementation than to the Mink project itself.

**Comment by oleg-andreyev** [comment]
@andrewnicols thanks for bringing this up. I understand and agree that this project has more chances to be recognized by the `php-webdriver` organization, and it will ensure that project won't be abandon. 

Initially, I wanted to update Selenium2Driver (https://github.com/minkphp/MinkSelenium2Driver/pull/304) to use `php-webdriver`, and IIRC there was a discussion about renaming the package, I tried to push Selenium2Driver forward, but I don't have access to merge PRs, but I got *sick* of slow responses... 

I would like to hear something from @OndraM and @stof as they have more experience in OSS and maintaining OSS packages.

**Comment by andrewnicols** [comment]
That was my experience too with the Selenium2 and Instaclick drivers, which is why I also opted to fork the driver.

I work full time writing OSS for Moodle.

I think that with whichever direction we go the best chance of success lie in a couple of places:
1. Discoverability; and
1. Maintenance.

For discoverability if we can work with @stof and others in the Mink project to get this driver listed officially in their docs and as a suggested package, that’s probably a good start.

In terms of maintenance, having appropriate CI, high code coverage, and multiple people able to contribute to the project are high on my list.

**Comment by andrewnicols** [comment]
Any chance we can move this forward? I feel that we should try and do this, and update PHP namespace etc. sooner rather than later.

**Comment by oleg-andreyev** [comment]
@andrewnicols the only reason why it's not yet done:
- I haven't got any response from @stof or @OndraM
- I'll lose maintainers access to the repository if I'll move it without a response from @stof or @OndraM

**Comment by OndraM** [comment]
Hi, sorry for the delay, I was on summer vacation :).

My first idea would by to try to use existing "minkphp" organization - from continuity reasons (as it already hosts drivers for Goutte, BrowserKite etc.) and discoverability (people will probably look for the driver on the same place as they found mink itself) . Do you have a response from @stof? But if you fell this won't work or there is no response/negative response from him, we may try going ahead with php-webdriver organization, I'm not strictly against it. But `minkphp` makes more sense me in context of the Mink project.

**Comment by oleg-andreyev** [comment]
As another solution is get into contacts with https://github.com/FriendsOfBehat they already have some forks for Mink.

**Comment by andrewnicols** [comment]
Yeah - I'm thinking either just release under your repo, or FoB.

Either way, I think we're close to ready.

I've had a bit of time to spend on this over the past three weeks and have most of our steps passing cleanly now. I have a few random fails to hunt down but otherwise I think I've found most of the problems.

I'm currently applying the following Pull requests for all of our runs:
- #8 
- #10
- #11 
- #12
